apiVersion: v1
kind: PersistentVolumeClaim
# Set up a requirement for a persistent volume for postgres DB
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi